config/routes.rb
Bookstore::Application.routes.draw do
  
  get "sessions/new"
  get "users/new"
  
  resources :titles
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/titles_search',  :to => 'shop#titles_search'
	match '/movie_show', :to => 'titles#show'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/signup',  :to => 'users#new'
  
	match '/watch_video', :to => 'shop#watch_video'
  match '/home_index', :to => 'shop#index'
  
  root :to => "shop#index"
  

end

app/models/title.rb
class Title < ActiveRecord::Base
	has_and_belongs_to_many :users
	attr_accessible :movie_name, :director, :image_url, :video_url, :rating

  validates_uniqueness_of :id
  validates_uniqueness_of :movie_name, :scope => :director
  validates_presence_of :movie_name, :director, :image_url, :video_url
  validates_numericality_of :rating
  # validates_numericality_of :inventory, :only_integer => true
 #  validates_format_of :image_url,
 #    :with		=> %r{\.(gif|jpg|png)$}i,
 #    :message	=> "must be a URL for a GIF, JPG, or PNG image"
	# validates_format_of :video_url,
 #    :with		=> %r{\.(webm)$}i,
 #    :message	=> "must be a URL for a WEBM video"
  
  # def decr_inventory(quantity)
    # self.inventory = self.inventory - quantity
	# redirect_to :controller => 'shop', :action => 'index' unless self.save
  # end
  
  protected
  def validate
    errors.add(:rating, "should be between 1 and 5") if rating.nil? || rating < 0 || rating > 5
  end
  
  # def self.find_books_for_sale
	def self.find_titles_for_sale
    find(:all, :order => "movie_name")
  end
  
  # Searches for titles when called from the controller using like
  def self.search(query)
    movie_name = query.to_s.gsub(/%/,"\%")
		movies_arr = []
		movies_arr << Title.find_by_movie_name(movie_name) unless Title.find_by_movie_name(movie_name) == nil
		movie_name.split(' ').each do |i|
			movies1 = Title.find(:all, :conditions => ["movie_name like ?", "%#{i}%"])
			movies1.each do |title|
				movies_arr << title unless movies_arr.include?(title)
			end
		end
		return movies_arr
  end

end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  @@BUCKET = "videoguru"
  # before_filter :run_before, :except => [:index, :show, :new, :edit, :destroy, :add_to_cart, :get_cart, :clear_cart, :view_cart]
  before_filter :run_before, :except => [:index, :show, :new, :edit, :destroy]
  
  def run_before
    params[:title][:movie_name] = params[:title][:movie_name].humanize.titleize
	  params[:title][:director] = params[:title][:director].humanize.titleize
  end
  
  # GET /titles
  # GET /titles.xml
  def index
    @titles = Title.all
	# @title = Title.new
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @titles }
    end
  end

  # GET /titles/1
  # GET /titles/1.xml
  def show
    puts "**************************"
		puts params[:id]
		@title = Title.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @title }
    end
  end

  # GET /titles/new
  # GET /titles/new.xml
  def new
    @title = Title.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @title }
    end
  end

  # GET /titles/1/edit
  def edit
		@title = Title.find(params[:id])
  end

  # POST /titles
  # POST /titles.xml
  def create
    @title = Title.new(params[:title])
    
  	fileUp = params[:upload]
    orig_filename =  fileUp['image_file'].original_filename
    filename = sanitize_filename(orig_filename)
    AWS::S3::S3Object.store(filename, fileUp['image_file'].read, @@BUCKET, :access => :public_read)
    imageurl = AWS::S3::S3Object.url_for(filename, @@BUCKET, :authenticated => false)
	@title.image_url = imageurl
    
    orig_filename =  fileUp['video_file'].original_filename
    filename = sanitize_filename(orig_filename)
    AWS::S3::S3Object.store(filename, fileUp['video_file'].read, @@BUCKET, :access => :public_read)
    videourl = AWS::S3::S3Object.url_for(filename, @@BUCKET, :authenticated => false)

    @title.video_url = videourl

	  # create_author(params[:q],params[:r])
	  # if @author != nil
		respond_to do |format|
			if @title.save
				# @author.titles << @title unless @author.titles.include? @title
				# @author = nil
				format.html { redirect_to(@title, :notice => 'Title was successfully created.') }
				# format.js
				format.xml  { render :xml => @title, :status => :created, :location => @title }
			else
				format.html { render :action => "new" }
				# format.js { render :action => 'create_error' }
				format.xml  { render :xml => @title.errors, :status => :unprocessable_entity }
			end
		end
	# else
	  # respond_to do |format|
	    # format.html { render :action => "new" }
		# correc the line below
		# format.xml { render :xml => {@author=>["Author name is not valid"]}, :status => :unprocessable_entity }
	  # end
	# end
  end

  # PUT /titles/1
  # PUT /titles/1.xml
  def update
    @title = Title.find(params[:id])
    # create_author(params[:q],params[:r])

    # if @author != nil
	  respond_to do |format|
			if @title.update_attributes(params[:title])
		  	# @author.titles << @title unless @author.titles.include? @title
				# if params[:checks] != nil
					# params[:checks].each do |s|
						# if @title.authors.count > 1
								# @title.authors.delete(Author.find_by_id(s))
						# end
					# end
				# end
		    # @author = nil
				format.html { redirect_to(@title, :notice => 'Title was successfully updated.') }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @title.errors, :status => :unprocessable_entity }
			end
	  end
	  # else
			# respond_to do |format|
				# flash.now[:error] = 'Author name not valid'
				# respond_to do |format|
					# format.html { render :action => "edit" }
				# end
			# end
		# end
  end

  def destroy
	@title = Title.find(params[:id])
	AWS::S3::S3Object.find(@title.image_url.gsub("http://s3.amazonaws.com/videoguru/",""), @@BUCKET).delete
	AWS::S3::S3Object.find(@title.video_url.gsub("http://s3.amazonaws.com/videoguru/",""), @@BUCKET).delete
    @title.destroy


    respond_to do |format|
      format.html { redirect_to(titles_url) }
      format.xml  { head :ok }
    end
  end
  
  private 
      def sanitize_filename(file_name)
        just_filename = File.basename(file_name)
        just_filename.sub(/[^\w\.\-]/,'_')
      end
  
end

app/views/titles/_form.html.erb
<%= form_for @title, :html => {:multipart => true, :accept => "image/gif,image/png,image/jpg"} do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% @title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_name %><br />
    <%= f.text_field :movie_name, :placeholder => 'Enter title here' %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director, :placeholder => 'Director name' %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating, :placeholder => 'Enter a number between 1 and 5' %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
	<%= file_field 'upload', 'image_file'  %>
    
  </div>

	<div class="field">
    <%= f.label :video_url %><br />
	  <%= file_field 'upload', 'video_file'  %>

  </div>
  <br>
  
  <%= submit_tag("Create") %>

<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form' %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

app/views/titles/index.html.erb
<h1>Project</h1>

<div id="title-list">
<table>
    <th>Image_URL</th>
		<th>Title</th>
    <th>Director</th>
    <th>Rating</th>
		<th>Video_URL</th>
  </tr>  
  <% for title in @titles %>
		<td><%= title.image_url %>
	  <td><%= title.movie_name %>
	  <td><%= title.director %>
	  <td><%= title.rating %>
	  <td><%= title.video_url %>
	  <td><%= link_to 'Show', title %></td>
		<td><%= link_to 'Edit', edit_title_path(title) %></td>
		<td><%= link_to 'Destroy', title, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'New Title', new_title_path %>
</div>

app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form' %>

<%= link_to 'Back', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @title.movie_name %>
</p>

<p>
  <b>Director:</b>
  <%= @title.director %>
</p>

<p>
  <b>Rating:</b>
  <%= @title.rating %>
</p>

<p>
  <b>Video:</b>
	<video id="trailer"  controls poster="<%= @title.image_url %>" width="634" height="428">
    <source src="<%= @title.video_url %>">
  </video>
</p>

<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>